#!/usr/bin/env python3
"""
Reads a Mosaic Data Model via Strategy REST API and generates:
  - <output>/raw_model.json   (raw JSON dump of all API calls)
  - <output>/summary.md       (human-readable markdown summary of the model)

Usage modes:

1) List available projects for the user profile:
   python3 fetch_model.py --base-url https://HOST/MicroStrategyLibrary \
       --username USER --list-projects

2) Find Mosaic dataModelId by name (free-text search, no GUID required):
   python3 fetch_model.py --base-url https://HOST/MicroStrategyLibrary \
       --username USER --project "Project Name" --find-model "partial name"

3) Read and summarize a Mosaic Data Model (with known dataModelId):
   python3 fetch_model.py \
     --base-url https://HOST/MicroStrategyLibrary \
     --username USER \
     --project "Project Name" \
     --data-model-id 3A82F20B2CC849B0970B289C86D8C83C \
     --output ./out

Password can be passed via --password or read from MSTR_PASSWORD environment
variable (recommended to keep credentials out of shell history).
"""

import argparse
import json
import os
import sys
from urllib.parse import urljoin

import requests


def parse_args():
    p = argparse.ArgumentParser(description="Reads and summarizes a Mosaic Data Model via Strategy REST API")
    p.add_argument("--base-url", required=True, help="E.g., https://host/MicroStrategyLibrary")
    p.add_argument("--username", default=None, help="Username (optional if --session-file is provided)")
    p.add_argument("--password", default=None, help="If omitted, read from MSTR_PASSWORD env var")
    p.add_argument("--login-mode", type=int, default=1, help="1=Standard, 16=LDAP, 4096=SSO")
    p.add_argument("--project", default=None, help="Project name (resolves projectId)")
    p.add_argument("--project-id", default=None, help="Project GUID, if already known")
    p.add_argument("--data-model-id", default=None, help="Mosaic Data Model GUID")
    p.add_argument("--output", default="./out", help="Output directory")
    p.add_argument("--verify-ssl", action="store_true", default=True)
    p.add_argument("--no-verify-ssl", dest="verify_ssl", action="store_false")
    p.add_argument("--session-file", default=None, help="Path to session JSON file (.mstr_session.json) generated by browser_auth.py")
    p.add_argument("--list-projects", action="store_true",
                    help="Authenticate and list available projects in profile, then exit")
    p.add_argument("--find-model", default=None,
                    help="Search Mosaic Data Models matching this term (requires --project or --project-id)")
    return p.parse_args()


def api(base_url, path):
    return urljoin(base_url.rstrip("/") + "/", "api/" + path.lstrip("/"))


def login(session, base_url, username, password, login_mode, verify_ssl):
    url = api(base_url, "auth/login")
    resp = session.post(
        url,
        json={"username": username, "password": password, "loginMode": login_mode},
        verify=verify_ssl,
        timeout=30,
    )
    if resp.status_code not in (200, 204):
        raise SystemExit(f"Login failed ({resp.status_code}): {resp.text[:500]}")
    token = resp.headers.get("X-MSTR-AuthToken")
    if not token:
        raise SystemExit("Login succeeded but no X-MSTR-AuthToken header was returned.")
    return token


def list_projects(session, base_url, headers, verify_ssl):
    url = api(base_url, "projects")
    resp = session.get(url, headers=headers, verify=verify_ssl, timeout=30)
    resp.raise_for_status()
    return resp.json()


def get_project_id(session, base_url, headers, project_name, verify_ssl):
    projects = list_projects(session, base_url, headers, verify_ssl)
    for proj in projects:
        if proj.get("name", "").strip().lower() == project_name.strip().lower():
            return proj["id"]
    names = ", ".join(p.get("name", "?") for p in projects)
    raise SystemExit(f"Project '{project_name}' not found. Available: {names}")


MOSAIC_DATA_MODEL_SUBTYPE = 776  # EMMA cube / Mosaic Data Model


def find_mosaic_models(session, base_url, headers, term, verify_ssl):
    url = api(base_url, "searches/results")
    params = {
        "name": term,
        "pattern": 4,  # contains
        "type": 3,     # report family (cubes/Mosaic belong here)
        "getAncestors": "false",
        "limit": -1,
        "certifiedStatus": "ALL",
    }
    resp = session.get(url, headers=headers, params=params, verify=verify_ssl, timeout=30)
    resp.raise_for_status()
    results = resp.json().get("result", [])
    return [r for r in results if r.get("subtype") == MOSAIC_DATA_MODEL_SUBTYPE]


def get_json(session, base_url, path, headers, verify_ssl, params=None):
    url = api(base_url, path)
    resp = session.get(url, headers=headers, params=params or {}, verify=verify_ssl, timeout=60)
    if resp.status_code == 404:
        return None
    resp.raise_for_status()
    return resp.json()


def get_list(session, base_url, path, headers, verify_ssl, list_key):
    data = get_json(session, base_url, path, headers, verify_ssl, params={"offset": 0, "limit": -1})
    if not data:
        return []
    return data.get(list_key, [])


def build_summary_md(model, tables, attributes, base_metrics, metrics, hierarchy):
    info = model.get("information", {})
    lines = []
    lines.append(f"# {info.get('name', '(unnamed)')}")
    if info.get("description"):
        lines.append(f"\n_{info['description']}_")
    lines.append("\n## Model Configuration")
    lines.append(f"- objectId: `{info.get('objectId')}`")
    lines.append(f"- dataServeMode: {model.get('dataServeMode')}")
    lines.append(f"- autoJoin: {model.get('autoJoin')}")
    lines.append(f"- readOnly: {model.get('readOnly')}")
    sampling = model.get("sampling") or {}
    if sampling:
        lines.append(f"- sampling: {sampling.get('type')} / {sampling.get('rowCount')} rows")
    partition = model.get("partition") or {}
    if partition:
        lines.append(f"- partition: {partition.get('mode')} ({partition.get('number')})")

    lines.append(f"\n## Tables ({len(tables)})")
    for t in tables:
        tinfo = t.get("information", {})
        lines.append(f"- **{tinfo.get('name')}** (`{tinfo.get('objectId')}`)")

    lines.append(f"\n## Attributes ({len(attributes)})")
    for a in attributes:
        ainfo = a.get("information", {})
        forms = a.get("forms", [])
        key_forms = [f["name"] for f in forms if f.get("isKeyForm")]
        lookup = forms[0].get("lookupTable", {}).get("name") if forms else "?"
        lines.append(
            f"- **{ainfo.get('name')}** — forms: {len(forms)}"
            f" (keys: {', '.join(key_forms) or '?'}) — table: {lookup}"
        )

    lines.append(f"\n## Base Metrics / Facts ({len(base_metrics)})")
    for m in base_metrics:
        minfo = m.get("information", {})
        expr = (m.get("expression") or {}).get("text", "")
        lines.append(f"- **{minfo.get('name')}** = `{expr}`")

    lines.append(f"\n## Derived Metrics ({len(metrics)})")
    for m in metrics:
        minfo = m.get("information", {})
        expr = (m.get("expression") or {}).get("text", "")
        lines.append(f"- **{minfo.get('name')}** = `{expr}`")

    if hierarchy:
        lines.append("\n## Hierarchy")
        lines.append(f"```json\n{json.dumps(hierarchy, indent=2, ensure_ascii=False)[:4000]}\n```")

    return "\n".join(lines)


def main():
    args = parse_args()
    session = requests.Session()
    token = None

    if args.session_file and os.path.exists(args.session_file):
        with open(args.session_file, "r", encoding="utf-8") as f:
            sess_data = json.load(f)
        token = sess_data.get("auth_token")
        cookies = sess_data.get("cookies", {})
        if cookies:
            session.cookies.update(cookies)
        if token:
            print(f"Using authentication token from session file ({args.session_file})...")

    if not token:
        password = args.password or os.environ.get("MSTR_PASSWORD")
        if not password:
            print("Please provide password via --password/MSTR_PASSWORD or supply a valid --session-file.", file=sys.stderr)
            sys.exit(1)
        print("Authenticating via username/password...")
        token = login(session, args.base_url, args.username, password, args.login_mode, args.verify_ssl)

    headers = {"X-MSTR-AuthToken": token, "Accept": "application/json"}

    try:
        # Mode 1: list available projects
        if args.list_projects:
            projects = list_projects(session, args.base_url, headers, args.verify_ssl)
            print(f"\n{len(projects)} project(s) accessible for this user:\n")
            for proj in projects:
                print(f"- {proj.get('name')}  (id: {proj.get('id')})  status={proj.get('status')}")
            return

        # Subsequent modes require projectId
        project_id = args.project_id
        if not project_id:
            if not args.project:
                raise SystemExit("Specify --project or --project-id (use --list-projects to view options)")
            project_id = get_project_id(session, args.base_url, headers, args.project, args.verify_ssl)
        headers["X-MSTR-ProjectID"] = project_id

        # Mode 2: find dataModelId by name
        if args.find_model:
            matches = find_mosaic_models(session, args.base_url, headers, args.find_model, args.verify_ssl)
            if not matches:
                print(f"No Mosaic Data Models found matching '{args.find_model}' in this project.")
                return
            print(f"\n{len(matches)} Mosaic Data Model(s) found:\n")
            for m in matches:
                print(f"- {m.get('name')}  (dataModelId: {m.get('id')})  modified: {m.get('dateModified')}")
            return

        # Mode 3: read and summarize model
        if not args.data_model_id:
            raise SystemExit("Specify --data-model-id (or use --find-model to search by name)")

        os.makedirs(args.output, exist_ok=True)
        return _fetch_and_summarize(session, args, headers, password)
    finally:
        try:
            session.post(api(args.base_url, "auth/logout"), headers=headers, verify=args.verify_ssl, timeout=15)
        except requests.RequestException:
            pass


def _fetch_and_summarize(session, args, headers, password):
    print("Fetching data model information...")
    model = get_json(session, args.base_url, f"model/dataModels/{args.data_model_id}", headers, args.verify_ssl)
    if model is None:
        raise SystemExit("Data model not found (404). Check the dataModelId and project ID.")

    print("Fetching tables, attributes, and metrics...")
    tables = get_list(session, args.base_url, f"model/dataModels/{args.data_model_id}/tables", headers, args.verify_ssl, "tables")
    attributes = get_list(session, args.base_url, f"model/dataModels/{args.data_model_id}/attributes", headers, args.verify_ssl, "attributes")
    base_metrics = get_list(session, args.base_url, f"model/dataModels/{args.data_model_id}/baseMetrics", headers, args.verify_ssl, "baseMetrics")
    metrics = get_list(session, args.base_url, f"model/dataModels/{args.data_model_id}/metrics", headers, args.verify_ssl, "metrics")

    print("Fetching hierarchy...")
    hierarchy = get_json(session, args.base_url, f"model/dataModels/{args.data_model_id}/hierarchy", headers, args.verify_ssl)

    raw = {
        "model": model,
        "tables": tables,
        "attributes": attributes,
        "baseMetrics": base_metrics,
        "metrics": metrics,
        "hierarchy": hierarchy,
    }
    with open(os.path.join(args.output, "raw_model.json"), "w", encoding="utf-8") as f:
        json.dump(raw, f, indent=2, ensure_ascii=False)

    # Initialize local versioning cache and working draft
    try:
        from model_cache_manager import init_cache
        init_cache(args.data_model_id, raw)
    except Exception as e:
        print(f"[Notice] Could not initialize versioning cache: {e}")

    print("Generating summary...")
    summary = build_summary_md(model, tables, attributes, base_metrics, metrics, hierarchy)
    with open(os.path.join(args.output, "summary.md"), "w", encoding="utf-8") as f:
        f.write(summary)

    print(f"\nDone. Files written to: {args.output}/raw_model.json and {args.output}/summary.md")


if __name__ == "__main__":
    main()
