"""
Helper script for interacting with Strategy via the official MSTrio Python SDK (mstrio-py).

Allows connecting to the environment (via direct credentials or session file from browser_auth.py),
listing projects, finding Mosaic models/cubes, and inspecting structural details.

Requirements:
  pip install mstrio-py
"""

import argparse
import json
import os
import sys

def parse_args():
    p = argparse.ArgumentParser(description="MSTrio SDK helper for querying and analyzing Mosaic Data Models")
    p.add_argument("--base-url", required=True, help="E.g., https://host/MicroStrategyLibrary")
    p.add_argument("--username", default=None)
    p.add_argument("--password", default=None)
    p.add_argument("--session-file", default=None, help="Path to .mstr_session.json generated by browser_auth.py")
    p.add_argument("--project", default=None, help="Strategy project name")
    p.add_argument("--list-projects", action="store_true", help="List available projects in environment")
    p.add_argument("--find-model", default=None, help="Search Mosaic models by name or keyword")
    p.add_argument("--data-model-id", default=None, help="Mosaic model ID to inspect via mstrio")
    return p.parse_args()


def connect_mstrio(base_url, username=None, password=None, session_file=None, project_name=None):
    try:
        from mstrio.connection import Connection
    except ImportError:
        print("The 'mstrio-py' library is not installed. Install by running:\n  pip install mstrio-py", file=sys.stderr)
        sys.exit(1)

    base_url = base_url.rstrip("/")
    if not base_url.endswith("/api"):
        base_url = f"{base_url}/api"

    if session_file and os.path.exists(session_file):
        with open(session_file, "r", encoding="utf-8") as f:
            sess_data = json.load(f)
        token = sess_data.get("auth_token")
        if token:
            print("[MSTrio] Connecting via session token from saved session...")
            conn = Connection(base_url=base_url, identity_token=token, project_name=project_name)
            return conn

    # Fallback to credentials
    pwd = password or os.environ.get("MSTR_PASSWORD")
    if not username or not pwd:
        print("Provide username/password (or MSTR_PASSWORD) or specify a valid --session-file.", file=sys.stderr)
        sys.exit(1)

    print("[MSTrio] Connecting via username and password...")
    conn = Connection(base_url=base_url, username=username, password=pwd, project_name=project_name)
    return conn


def main():
    args = parse_args()
    conn = connect_mstrio(args.base_url, args.username, args.password, args.session_file, args.project)

    try:
        if args.list_projects:
            from mstrio.project_objects import Project
            projects = Project.get_projects(conn)
            print(f"\n{len(projects)} project(s) found:\n")
            for p in projects:
                print(f"- {p.name} (ID: {p.id}) | Status: {p.status}")
            return

        if args.find_model:
            from mstrio.project_objects import SuperCube
            print(f"\nSearching Mosaic models/cubes containing '{args.find_model}'...")
            cubes = SuperCube.find_cubes(conn, name=args.find_model)
            if not cubes:
                print("No models/cubes found.")
                return
            print(f"\n{len(cubes)} model(s) found:\n")
            for c in cubes:
                print(f"- {c.name} (ID: {c.id}) | Modified: {c.date_modified}")
            return

        if args.data_model_id:
            from mstrio.project_objects import SuperCube
            print(f"\nInspecting model ID: {args.data_model_id} via MSTrio SDK...")
            cube = SuperCube(conn, id=args.data_model_id)
            print(f"Name: {cube.name}")
            print(f"Description: {cube.description or '(no description)'}")
            print(f"Attributes ({len(cube.attributes)}):")
            for attr in cube.attributes:
                print(f"  - {attr['name']} (ID: {attr['id']})")
            print(f"Metrics ({len(cube.metrics)}):")
            for mtr in cube.metrics:
                print(f"  - {mtr['name']} (ID: {mtr['id']})")
            return

        print("No action specified. Use --list-projects, --find-model, or --data-model-id.")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
